// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OficinaJD.API.Data;

#nullable disable

namespace OficinaJD.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531215905_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OficinaJD.API.Models.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoJD")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("modelos", (string)null);
                });

            modelBuilder.Entity("OficinaJD.API.Models.Peca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Localizacao")
                        .HasColumnType("text");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("pecas", (string)null);
                });

            modelBuilder.Entity("OficinaJD.API.Models.PecaModelo", b =>
                {
                    b.Property<int>("PecaId")
                        .HasColumnType("integer");

                    b.Property<int>("ModeloId")
                        .HasColumnType("integer");

                    b.HasKey("PecaId", "ModeloId");

                    b.HasIndex("ModeloId");

                    b.ToTable("pecas_modelos", (string)null);
                });

            modelBuilder.Entity("OficinaJD.API.Models.PecaModelo", b =>
                {
                    b.HasOne("OficinaJD.API.Models.Modelo", "Modelo")
                        .WithMany("PecaModelos")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OficinaJD.API.Models.Peca", "Peca")
                        .WithMany("PecaModelos")
                        .HasForeignKey("PecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modelo");

                    b.Navigation("Peca");
                });

            modelBuilder.Entity("OficinaJD.API.Models.Modelo", b =>
                {
                    b.Navigation("PecaModelos");
                });

            modelBuilder.Entity("OficinaJD.API.Models.Peca", b =>
                {
                    b.Navigation("PecaModelos");
                });
#pragma warning restore 612, 618
        }
    }
}
